/**
 * Point d'entrée centralisé pour toutes les queries du module Informations
 * Exporte toutes les requêtes SQL organisées par responsabilité
 */

// ============================================================================
// QUERIES DE LECTURE
// ============================================================================

export {
  // Informations basiques
  SELECT_ALL_INFORMATIONS,
  SELECT_ALL_INFORMATIONS_WITH_INACTIVE,
  SELECT_INFORMATION_BY_ID,
  SELECT_ACTIVE_INFORMATION_BY_ID,
  SELECT_INFORMATIONS_WITH_RELATIONS,
  SELECT_INFORMATION_WITH_RELATIONS_BY_ID,

  // Filtres et recherche
  SEARCH_INFORMATIONS_BY_TITRE,
  SEARCH_INFORMATIONS_BY_CONTENU,
  SEARCH_INFORMATIONS_FULL_TEXT,
  SELECT_INFORMATIONS_BY_CATEGORIE,
  SELECT_INFORMATIONS_BY_AUTEUR,
  SELECT_INFORMATIONS_BY_STATUS,
  SELECT_INFORMATIONS_BY_PRIORITE,
  SELECT_INFORMATIONS_VISIBLE,
  SELECT_INFORMATIONS_BY_DATE_RANGE,
  SELECT_RECENT_INFORMATIONS,
  SELECT_HIGH_PRIORITY_INFORMATIONS,

  // Référentiels
  SELECT_ALL_STATUS,
  SELECT_STATUS_BY_ID,
  SELECT_ALL_GENRES,
  SELECT_GENRE_BY_ID,
  SELECT_ALL_GRADES,
  SELECT_GRADE_BY_ID,
  SELECT_ALL_PLANS_TARIFAIRES,
  SELECT_PLAN_TARIFAIRE_BY_ID,
  SELECT_ALL_CATEGORIES,
  SELECT_CATEGORIE_BY_ID,

  // Comptage
  COUNT_ALL_INFORMATIONS,
  COUNT_INFORMATIONS_BY_CATEGORIE,
  COUNT_INFORMATIONS_BY_STATUS,
  COUNT_INFORMATIONS_BY_PRIORITE,
  COUNT_RECENT_INFORMATIONS,

  // Pagination
  SEARCH_INFORMATIONS_BASE,
  COUNT_SEARCH_RESULTS,
} from './read.queries.js';

// ============================================================================
// QUERIES D'ÉCRITURE
// ============================================================================

export {
  // Insertion - Informations
  INSERT_INFORMATION,
  INSERT_INFORMATION_FULL,
  INSERT_INFORMATION_MINIMAL,

  // Mise à jour - Informations
  UPDATE_INFORMATION,
  UPDATE_INFORMATION_TITRE,
  UPDATE_INFORMATION_CONTENU,
  UPDATE_INFORMATION_CATEGORIE,
  UPDATE_INFORMATION_PRIORITE,
  UPDATE_INFORMATION_VISIBLE,
  UPDATE_INFORMATION_STATUS,
  UPDATE_INFORMATION_PARTIAL_BASE,

  // Suppression - Informations
  DELETE_INFORMATION,
  SOFT_DELETE_INFORMATION,
  ARCHIVE_INFORMATION,
  RESTORE_INFORMATION,
  PUBLISH_INFORMATION,
  DRAFT_INFORMATION,
  DELETE_INFORMATIONS_BY_CATEGORIE,
  DELETE_INFORMATIONS_BY_AUTEUR,
  DELETE_OLD_INFORMATIONS,

  // Insertion - Catégories
  INSERT_CATEGORIE,

  // Mise à jour - Catégories
  UPDATE_CATEGORIE,
  UPDATE_CATEGORIE_NOM,

  // Suppression - Catégories
  DELETE_CATEGORIE,

  // Historique
  INSERT_HISTORIQUE,
  DELETE_HISTORIQUE_BY_INFORMATION,

  // Vues/Tracking
  INSERT_VUE,
  INCREMENT_VUES_COUNT,

  // Notifications
  INSERT_NOTIFICATION,
  MARK_NOTIFICATION_READ,
  MARK_ALL_NOTIFICATIONS_READ,
  DELETE_NOTIFICATIONS_BY_INFORMATION,

  // Maintenance
  CLEANUP_OLD_VUES,
  CLEANUP_OLD_NOTIFICATIONS,
  AUTO_ARCHIVE_OLD_INFORMATIONS,
  RESET_VUES_COUNT,

  // Batch
  UPDATE_MULTIPLE_INFORMATIONS_STATUS,
  DELETE_MULTIPLE_INFORMATIONS,
  ARCHIVE_MULTIPLE_INFORMATIONS,
  RESTORE_MULTIPLE_INFORMATIONS,
} from './write.queries.js';

// ============================================================================
// QUERIES DE VALIDATION
// ============================================================================

export {
  // Vérification d'existence
  CHECK_INFORMATION_EXISTS,
  CHECK_ACTIVE_INFORMATION_EXISTS,
  CHECK_CATEGORIE_EXISTS,
  CHECK_AUTEUR_EXISTS,
  CHECK_STATUS_EXISTS,

  // Vérification de doublons
  CHECK_DUPLICATE_TITRE,
  CHECK_DUPLICATE_TITRE_NEW,
  CHECK_DUPLICATE_CATEGORIE,
  CHECK_DUPLICATE_CATEGORIE_NEW,

  // Validation de permissions
  CHECK_CAN_EDIT_INFORMATION,
  CHECK_IS_AUTHOR,
  CHECK_IS_ADMIN_OR_MANAGER,

  // Validation de statut
  CHECK_IS_PUBLISHED,
  CHECK_IS_DRAFT,
  CHECK_IS_ARCHIVED,
  CHECK_IS_DELETED,
  CHECK_IS_VISIBLE,

  // Validation de dates
  CHECK_RECENTLY_MODIFIED,
  CHECK_IS_RECENT,

  // Validation de dépendances
  CHECK_CATEGORIE_HAS_INFORMATIONS,
  CHECK_AUTEUR_HAS_INFORMATIONS,
  CHECK_HAS_ACTIVE_NOTIFICATIONS,
  CHECK_HAS_HISTORIQUE,

  // Validation de contenu
  VALIDATE_TITRE_LENGTH,
  VALIDATE_CONTENU_LENGTH,
  VALIDATE_PRIORITE,

  // Validation complète
  VALIDATE_INFORMATION_COMPLETE,
  CHECK_CAN_PUBLISH,
  CHECK_CAN_ARCHIVE,
  CHECK_CAN_RESTORE,
  CHECK_CAN_DELETE,

  // Comptage pour validation
  COUNT_ACTIVE_INFORMATIONS_BY_CATEGORIE,
  COUNT_DRAFTS_BY_AUTEUR,
  COUNT_PUBLISHED_BY_AUTEUR,
} from './validation.queries.js';
