# Définir une variable pour le jeton
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTU0LCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJzdGF0dXNfaWQiOjQsImlhdCI6MTY5MjAwMDAwMCwiZXhwIjoxNjkyMDg2NDAwfQ.abc123exampletoken

###

# Test de la route de connexion (Login)
POST https://clubmanagment.com/api/auth/login
Content-Type: application/json

{
  "email": "houthoofd.benoit48@gmail.com",
  "password": "PtW143kjkS3F!"
}

###

# Test de la route de déconnexion (Logout)
POST https://clubmanagment.com/api/auth/logout
Content-Type: application/json

###

# Test de la vérification du token (Verify)
GET https://clubmanagment.com/api/auth/verify
Authorization: Bearer {{token}}

###

# Test de la génération d'un nouveau token (Refresh)
POST https://clubmanagment.com/api/auth/refresh
Authorization: Bearer {{token}}

###

# Test de la route publique (Test)
GET https://clubmanagment.com/api/auth/test

###

# Test de la récupération du statut utilisateur (Status)
GET https://clubmanagment.com/api/auth/status
Authorization: Bearer {{token}}