## Exemple pour récupèrer les cours
POST http://localhost:3000/cours
Content-Type: application/json

{
  "nom": "Houthoofd",
  "prenom": "Benoit"
}
###

GET http://localhost:3000/cours/3?extended

###

GET http://localhost:3000/cours/3/

###

PUT http://localhost:3000/cours/inscription/validation

###

## Exemple pour récupèrer les cours
GET http://localhost:3000/cours/informations/planning
