## Exemple pour récupèrer les grades
GET https://clubmanagment.com/api/informations/grades

###

## Exemple pour récupèrer les status
GET https://clubmanagment.com/api/informations/status

###

## Exemple pour récupèrer les status
GET https://clubmanagment.com/api/informations/abonnements

###

## Exemple pour récupèrer les status
GET https://clubmanagment.com/api/informations/genres



