#!/bin/bash

echo "🎯 Next Formatters to Fix"
echo "========================"
echo ""
echo "1. message-formatters.test.ts"
echo "   Location: src/features/messages/utils/__tests__/utils/"
echo "   Source: src/features/messages/utils/message-formatters.ts"
echo ""
echo "2. product-formatters.test.ts"
echo "   Location: src/features/shop/utils/__tests__/utils/"
echo "   Source: src/features/shop/utils/product-formatters.ts"
echo ""
echo "3. user-formatters.test.ts"
echo "   Location: src/features/users/utils/__tests__/utils/"
echo "   Source: src/features/users/utils/user-formatters.ts"
echo ""
echo "Pattern to follow: teacher-formatters.test.ts & course-formatters.test.ts"
echo "Estimated time: 20-30 min per file"
