### Informations endpoints

# Récupérer les informations générales du club
GET http://localhost:3000/informations/abonnements
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTU1LCJlbWFpbCI6ImhvdXRob29mZC5iZW5vaXQ0OEBnbWFpbC5jb20iLCJzdGF0dXNfaWQiOjQsImlhdCI6MTc1ODc3ODQxMCwiZXhwIjoxNzU4ODY0ODEwfQ.9f1V1UDn8dQHfbO2K1kAy68EMr3_IjrpZTT9W5fwhFE

# Récupérer les informations générales du club
### Récupérer les grades
GET http://localhost:3000/informations/grades
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTU1LCJlbWFpbCI6ImhvdXRob29mZC5iZW5vaXQ0OEBnbWFpbC5jb20iLCJzdGF0dXNfaWQiOjQsImlhdCI6MTc1ODc3ODQxMCwiZXhwIjoxNzU4ODY0ODEwfQ.9f1V1UDn8dQHfbO2K1kAy68EMr3_IjrpZTT9W5fwhFE

# Récupérer les informations générales du club
GET http://localhost:3000/informations/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTU1LCJlbWFpbCI6ImhvdXRob29mZC5iZW5vaXQ0OEBnbWFpbC5jb20iLCJzdGF0dXNfaWQiOjQsImlhdCI6MTc1ODc3ODQxMCwiZXhwIjoxNzU4ODY0ODEwfQ.9f1V1UDn8dQHfbO2K1kAy68EMr3_IjrpZTT9W5fwhFE

# Récupérer les informations générales du club
### Récupérer les genres
GET http://localhost:3000/informations/genres
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTU1LCJlbWFpbCI6ImhvdXRob29mZC5iZW5vaXQ0OEBnbWFpbC5jb20iLCJzdGF0dXNfaWQiOjQsImlhdCI6MTc1ODc3ODQxMCwiZXhwIjoxNzU4ODY0ODEwfQ.9f1V1UDn8dQHfbO2K1kAy68EMr3_IjrpZTT9W5fwhFE

# Récupérer les informations générales du club
GET http://localhost:3000/informations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTU1LCJlbWFpbCI6ImhvdXRob29mZC5iZW5vaXQ0OEBnbWFpbC5jb20iLCJzdGF0dXNfaWQiOjQsImlhdCI6MTc1ODc3ODQxMCwiZXhwIjoxNzU4ODY0ODEwfQ.9f1V1UDn8dQHfbO2K1kAy68EMr3_IjrpZTT9W5fwhFE

### Récupérer le planning des cours
GET http://localhost:3000/informations/planning
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTU1LCJlbWFpbCI6ImhvdXRob29mZC5iZW5vaXQ0OEBnbWFpbC5jb20iLCJzdGF0dXNfaWQiOjQsImlhdCI6MTc1ODc3ODQxMCwiZXhwIjoxNzU4ODY0ODEwfQ.9f1V1UDn8dQHfbO2K1kAy68EMr3_IjrpZTT9W5fwhFE
uthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTU1LCJlbWFpbCI6ImhvdXRob29mZC5iZW5vaXQ0OEBnbWFpbC5jb20iLCJzdGF0dXNfaWQiOjQsImlhdCI6MTc1ODc3ODQxMCwiZXhwIjoxNzU4ODY0ODEwfQ.9f1V1UDn8dQHfbO2K1kAy68EMr3_IjrpZTT9W5fwhFE



