/**
 * Index des services du module statistiques
 * Exporte tous les services pour faciliter les imports
 */

export {
  obtenirStatistiquesFrequentation,
  obtenirProgressionUtilisateur,
  obtenirPresenceParMois,
  getNombreMembres,
  getTotalPaiementsMois,
  getPaiementsRecents,
  getPaiementsEnAttente,
  getPlansActifs,
  getTauxRenouvellement,
  getPaiementsParMois,
  getMembresParPlan,
  getDerniersPaiements,
  getPaiementsEchus,
  getNouveauxMembres,
  getTopMembresAssidus,
  getMembresParGrade,
  getMembresParGenre,
  getProchainsAnniversaires,
  getArticlesPlusVendus,
  getCoursSemaine,
  type FrequentationData,
  type ProgressionData,
  type PresenceParMoisData,
  type StatistiqueSimple,
  type PaiementParMois,
  type MembreParPlan,
  type DernierPaiement,
  type PaiementEchu,
  type NouveauMembre,
  type MembreAssidu,
  type MembreParGrade,
  type MembreParGenre,
  type Anniversaire,
  type ArticleVendu,
} from './statistiques.service.js';
