/**
 * COMPLETE STACK EXAMPLE - Full Integration
 *
 * This file demonstrates how to use ALL the tools together:
 * ✅ GraphQL + Apollo Client (with generated hooks)
 * ✅ Zustand (state management)
 * ✅ HOCs (withAuth, withTracking, withErrorBoundary)
 * ✅ i18n (translations)
 * ✅ Loading/Error handling
 * ✅ Type safety
 *
 * ARCHITECTURE OVERVIEW:
 *
 * 1. GraphQL Layer (Data)
 *    - Apollo Client queries/mutations
 *    - Auto-generated TypeScript hooks
 *    - Type-safe operations
 *
 * 2. Zustand Layer (State)
 *    - Global state (auth, cart, UI)
 *    - Persistent stores
 *    - Optimistic updates
 *
 * 3. i18n Layer (Localization)
 *    - Multi-language support
 *    - Formatted dates/currency
 *    - Type-safe translations
 *
 * 4. HOC Layer (Cross-cutting concerns)
 *    - Authentication
 *    - Analytics tracking
 *    - Error boundaries
 *    - Loading states
 *
 * EXAMPLE: User Management Page
 * - Fetches users with GraphQL
 * - Stores auth in Zustand
 * - Translates UI with i18n
 * - Protected with HOCs
 * - Tracks analytics
 */

import React, { useEffect, useState } from 'react';
import {
  PageSection,
  Title,
  Button,
  Card,
  CardBody,
  Grid,
  GridItem,
  Alert,
  Modal,
  Form,
  FormGroup,
  TextInput,
} from '@patternfly/react-core';
import { PlusIcon, TrashIcon, EditIcon } from '@patternfly/react-icons';

// ============================================================================
// 1. GRAPHQL + APOLLO - Generated hooks from codegen
// ============================================================================

import {
  // Auto-generated by GraphQL Code Generator
  useGetUsersQuery,
  useCreateUserMutation,
  useUpdateUserMutation,
  useDeleteUserMutation,
  GetUsersDocument,
  User,
  CreateUserInput,
  UpdateUserInput,
} from '@/core/api/apollo/generated/graphql';

// ============================================================================
// 2. ZUSTAND - State Management
// ============================================================================

import { useAuthStore, selectUser, selectIsAuthenticated } from '@/store/authStore';
import { useCartStore } from '@/store/cartStore';
import {
  useUIStore,
  showSuccessNotification,
  showErrorNotification
} from '@/store/uiStore';

// ============================================================================
// 3. i18n - Internationalization
// ============================================================================

import {
  useTypedTranslation,
  formatDate,
  formatCurrency
} from '@/core/i18n/translationHelpers';

// ============================================================================
// 4. HOCs - Higher Order Components
// ============================================================================

import { withTracking, useTracking } from '@/hocs/withTracking';
import { withAuth } from '@/hocs/withAuth';
import { withErrorBoundary } from '@/hocs/withErrorBoundary';
import { useLoadingWrapper } from '@/hocs/withLoading';
import { SimpleLoadingState, SimpleErrorState } from '@/hocs/withData';

// ============================================================================
// TYPES
// ============================================================================

interface UserFormData {
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
}

interface UserManagementPageProps {
  // Props can be passed from router, etc.
  initialFilter?: string;
}

// ============================================================================
// COMPONENT
// ============================================================================

const UserManagementPageComponent: React.FC<UserManagementPageProps> = ({
  initialFilter
}) => {
  // ============================================================================
  // HOOKS SETUP
  // ============================================================================

  // i18n
  const { t } = useTypedTranslation();

  // Tracking
  const { trackEvent } = useTracking();

  // Loading wrapper
  const { wrapAsync, isLoading: isSaving } = useLoadingWrapper({
    loadingMessage: t('common.messages.saving', 'Enregistrement...'),
  });

  // Zustand stores
  const currentUser = useAuthStore(selectUser);
  const isAuthenticated = useAuthStore(selectIsAuthenticated);
  const cartCount = useCartStore((state) => state.getTotalItems());
  const { openModal, closeModal, activeModal } = useUIStore();

  // ============================================================================
  // GRAPHQL QUERIES & MUTATIONS
  // ============================================================================

  // Query: Get all users (auto-generated hook)
  const {
    data: usersData,
    loading: usersLoading,
    error: usersError,
    refetch: refetchUsers,
  } = useGetUsersQuery({
    // Apollo options
    fetchPolicy: 'cache-and-network',
    notifyOnNetworkStatusChange: true,
    onCompleted: (data) => {
      console.log('✅ Users loaded:', data.users?.length);
      trackEvent('Users List Loaded', {
        count: data.users?.length || 0,
      });
    },
    onError: (error) => {
      console.error('❌ Users load error:', error);
      trackEvent('Users List Load Error', {
        error: error.message,
      });
      showErrorNotification(
        t('errors.generic', 'Erreur'),
        t('users.list.loadError', 'Impossible de charger les utilisateurs')
      );
    },
  });

  // Mutation: Create user
  const [createUserMutation] = useCreateUserMutation({
    // Optimistic update
    optimisticResponse: (vars) => ({
      __typename: 'Mutation',
      createUser: {
        __typename: 'User',
        id: -1, // Temporary ID
        first_name: vars.input.first_name,
        last_name: vars.input.last_name,
        email: vars.input.email,
        phone: vars.input.phone || null,
        role: 'member',
        active: true,
        created_at: new Date().toISOString(),
      },
    }),
    // Update cache after mutation
    update: (cache, { data }) => {
      if (!data?.createUser) return;

      // Read current cache
      const existing = cache.readQuery({ query: GetUsersDocument });

      if (existing?.users) {
        // Write updated cache
        cache.writeQuery({
          query: GetUsersDocument,
          data: {
            users: [...existing.users, data.createUser],
          },
        });
      }
    },
    onCompleted: (data) => {
      trackEvent('User Created', { userId: data.createUser?.id });
      showSuccessNotification(
        t('users.create.success', 'Succès'),
        t('users.create.successMessage', 'Utilisateur créé avec succès')
      );
    },
    onError: (error) => {
      trackEvent('User Create Error', { error: error.message });
      showErrorNotification(
        t('errors.generic', 'Erreur'),
        error.message
      );
    },
  });

  // Mutation: Update user
  const [updateUserMutation] = useUpdateUserMutation({
    onCompleted: () => {
      trackEvent('User Updated');
      showSuccessNotification(
        t('common.messages.success', 'Succès'),
        t('users.edit.success', 'Utilisateur mis à jour')
      );
    },
  });

  // Mutation: Delete user
  const [deleteUserMutation] = useDeleteUserMutation({
    // Remove from cache optimistically
    update: (cache, { data }, { variables }) => {
      if (!data?.deleteUser || !variables) return;

      cache.modify({
        fields: {
          users(existingUsers = [], { readField }) {
            return existingUsers.filter(
              (userRef: any) => readField('id', userRef) !== variables.id
            );
          },
        },
      });
    },
    onCompleted: () => {
      trackEvent('User Deleted');
      showSuccessNotification(
        t('common.messages.success', 'Succès'),
        t('users.delete.success', 'Utilisateur supprimé')
      );
    },
  });

  // ============================================================================
  // LOCAL STATE
  // ============================================================================

  const [searchTerm, setSearchTerm] = useState(initialFilter || '');
  const [selectedUser, setSelectedUser] = useState<User | null>(null);
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [formData, setFormData] = useState<UserFormData>({
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
  });

  // ============================================================================
  // COMPUTED VALUES
  // ============================================================================

  // Filter users based on search
  const filteredUsers = React.useMemo(() => {
    if (!usersData?.users) return [];

    return usersData.users.filter((user) => {
      const searchLower = searchTerm.toLowerCase();
      return (
        user.first_name?.toLowerCase().includes(searchLower) ||
        user.last_name?.toLowerCase().includes(searchLower) ||
        user.email?.toLowerCase().includes(searchLower)
      );
    });
  }, [usersData?.users, searchTerm]);

  // ============================================================================
  // HANDLERS
  // ============================================================================

  const handleCreateUser = async () => {
    trackEvent('User Create Form Submit', {
      timestamp: new Date().toISOString(),
    });

    wrapAsync(async () => {
      const input: CreateUserInput = {
        first_name: formData.firstName,
        last_name: formData.lastName,
        email: formData.email,
        phone: formData.phone,
      };

      await createUserMutation({
        variables: { input },
      });

      // Reset form
      setFormData({
        firstName: '',
        lastName: '',
        email: '',
        phone: '',
      });
      setIsFormOpen(false);
    });
  };

  const handleUpdateUser = async (userId: number) => {
    trackEvent('User Update', { userId });

    wrapAsync(async () => {
      const input: UpdateUserInput = {
        first_name: formData.firstName,
        last_name: formData.lastName,
        email: formData.email,
        phone: formData.phone,
      };

      await updateUserMutation({
        variables: { id: userId, input },
      });

      setSelectedUser(null);
      setIsFormOpen(false);
    });
  };

  const handleDeleteUser = async (userId: number) => {
    const confirmMessage = t(
      'users.delete.confirm',
      'Êtes-vous sûr de vouloir supprimer cet utilisateur ?'
    );

    if (!window.confirm(confirmMessage)) return;

    trackEvent('User Delete Confirmed', { userId });

    wrapAsync(async () => {
      await deleteUserMutation({
        variables: { id: userId },
      });
    });
  };

  const handleEditUser = (user: User) => {
    trackEvent('User Edit Click', { userId: user.id });

    setSelectedUser(user);
    setFormData({
      firstName: user.first_name || '',
      lastName: user.last_name || '',
      email: user.email || '',
      phone: user.phone || '',
    });
    setIsFormOpen(true);
  };

  const handleSearch = (value: string) => {
    setSearchTerm(value);
    trackEvent('Users Search', { searchTerm: value });
  };

  // ============================================================================
  // EFFECTS
  // ============================================================================

  // Track page view
  useEffect(() => {
    trackEvent('User Management Page View', {
      timestamp: new Date().toISOString(),
      userRole: currentUser?.role,
    });
  }, []);

  // Auto-save search term to Zustand UI store
  useEffect(() => {
    if (searchTerm) {
      // Could store in UI store for persistence
      console.log('Search term:', searchTerm);
    }
  }, [searchTerm]);

  // ============================================================================
  // RENDER HELPERS
  // ============================================================================

  const renderUserCard = (user: User) => (
    <Card key={user.id} isCompact>
      <CardBody>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <strong>{user.first_name} {user.last_name}</strong>
            <br />
            <small style={{ color: '#6c757d' }}>{user.email}</small>
            <br />
            <small>
              {t('users.fields.joinDate', 'Membre depuis')}: {' '}
              {user.created_at ? formatDate(new Date(user.created_at), 'short') : 'N/A'}
            </small>
          </div>
          <div style={{ display: 'flex', gap: '0.5rem' }}>
            <Button
              variant="secondary"
              icon={<EditIcon />}
              onClick={() => handleEditUser(user)}
            >
              {t('common.actions.edit', 'Modifier')}
            </Button>
            <Button
              variant="danger"
              icon={<TrashIcon />}
              onClick={() => handleDeleteUser(user.id)}
            >
              {t('common.actions.delete', 'Supprimer')}
            </Button>
          </div>
        </div>
      </CardBody>
    </Card>
  );

  // ============================================================================
  // LOADING & ERROR STATES
  // ============================================================================

  if (usersLoading && !usersData) {
    return (
      <SimpleLoadingState
        message={t('users.list.loading', 'Chargement des utilisateurs...')}
      />
    );
  }

  if (usersError) {
    return (
      <SimpleErrorState
        title={t('errors.generic', 'Une erreur est survenue')}
        message={usersError.message}
        onRetry={() => refetchUsers()}
      />
    );
  }

  // ============================================================================
  // MAIN RENDER
  // ============================================================================

  return (
    <PageSection>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <div>
          <Title headingLevel="h1">
            {t('users.list.title', 'Gestion des utilisateurs')}
          </Title>
          <p style={{ color: '#6c757d', marginTop: '0.5rem' }}>
            {t('users.list.subtitle', 'Total: {{count}} utilisateurs', {
              count: filteredUsers.length
            })}
          </p>
        </div>
        <Button
          variant="primary"
          icon={<PlusIcon />}
          onClick={() => {
            trackEvent('Add User Button Click');
            setSelectedUser(null);
            setFormData({
              firstName: '',
              lastName: '',
              email: '',
              phone: '',
            });
            setIsFormOpen(true);
          }}
        >
          {t('users.list.addUser', 'Ajouter un utilisateur')}
        </Button>
      </div>

      {/* Zustand Store Info (debug) */}
      {currentUser && (
        <Alert
          variant="info"
          title={t('auth.session.active', 'Session active')}
          isInline
          style={{ marginBottom: '1rem' }}
        >
          {t('auth.session.loggedAs', 'Connecté en tant que')}: {currentUser.first_name} {currentUser.last_name}
          {' | '}
          {t('shop.cart.items', 'Panier')}: {cartCount} {t('shop.cart.itemsCount', 'articles')}
        </Alert>
      )}

      {/* Search */}
      <TextInput
        type="search"
        placeholder={t('users.list.search', 'Rechercher des utilisateurs...')}
        value={searchTerm}
        onChange={(_event, value) => handleSearch(value)}
        style={{ marginBottom: '1rem' }}
      />

      {/* User List */}
      {filteredUsers.length === 0 ? (
        <Alert variant="warning" title={t('users.list.noUsers', 'Aucun utilisateur trouvé')} />
      ) : (
        <Grid hasGutter>
          {filteredUsers.map((user) => (
            <GridItem key={user.id} span={6}>
              {renderUserCard(user)}
            </GridItem>
          ))}
        </Grid>
      )}

      {/* Create/Edit User Modal */}
      <Modal
        isOpen={isFormOpen}
        onClose={() => setIsFormOpen(false)}
        title={selectedUser
          ? t('users.edit.title', 'Modifier l\'utilisateur')
          : t('users.create.title', 'Ajouter un utilisateur')
        }
        variant="medium"
        actions={[
          <Button
            key="confirm"
            variant="primary"
            onClick={() => selectedUser
              ? handleUpdateUser(selectedUser.id)
              : handleCreateUser()
            }
            isLoading={isSaving}
            isDisabled={isSaving}
          >
            {isSaving
              ? t('common.messages.saving', 'Enregistrement...')
              : t('common.actions.save', 'Enregistrer')
            }
          </Button>,
          <Button
            key="cancel"
            variant="link"
            onClick={() => setIsFormOpen(false)}
            isDisabled={isSaving}
          >
            {t('common.actions.cancel', 'Annuler')}
          </Button>,
        ]}
      >
        <Form>
          <FormGroup
            label={t('users.fields.firstName', 'Prénom')}
            isRequired
            fieldId="firstName"
          >
            <TextInput
              id="firstName"
              value={formData.firstName}
              onChange={(_event, value) => setFormData({ ...formData, firstName: value })}
              isRequired
            />
          </FormGroup>

          <FormGroup
            label={t('users.fields.lastName', 'Nom')}
            isRequired
            fieldId="lastName"
          >
            <TextInput
              id="lastName"
              value={formData.lastName}
              onChange={(_event, value) => setFormData({ ...formData, lastName: value })}
              isRequired
            />
          </FormGroup>

          <FormGroup
            label={t('users.fields.email', 'Email')}
            isRequired
            fieldId="email"
          >
            <TextInput
              id="email"
              type="email"
              value={formData.email}
              onChange={(_event, value) => setFormData({ ...formData, email: value })}
              isRequired
            />
          </FormGroup>

          <FormGroup
            label={t('users.fields.phone', 'Téléphone')}
            fieldId="phone"
          >
            <TextInput
              id="phone"
              value={formData.phone}
              onChange={(_event, value) => setFormData({ ...formData, phone: value })}
            />
          </FormGroup>
        </Form>
      </Modal>
    </PageSection>
  );
};

// ============================================================================
// EXPORT WITH HOCS
// ============================================================================

// Apply multiple HOCs (order matters!)
const UserManagementPage = withErrorBoundary(
  withAuth(
    withTracking(UserManagementPageComponent, 'UserManagementPage')
  )
);

export default UserManagementPage;

/**
 * ============================================================================
 * SUMMARY - WHAT THIS EXAMPLE DEMONSTRATES
 * ============================================================================
 *
 * ✅ GraphQL + Apollo Client
 *    - Auto-generated hooks (useGetUsersQuery, useCreateUserMutation)
 *    - Type-safe queries and mutations
 *    - Optimistic updates
 *    - Cache management
 *    - Error/loading states
 *
 * ✅ Zustand State Management
 *    - authStore: Current user, authentication
 *    - cartStore: Shopping cart state
 *    - uiStore: Notifications, modals
 *    - Persistent stores
 *
 * ✅ i18n Internationalization
 *    - useTypedTranslation hook
 *    - All UI strings translated
 *    - Formatted dates with formatDate
 *    - Interpolation ({{count}} users)
 *
 * ✅ HOCs (Higher-Order Components)
 *    - withAuth: Protects page (requires authentication)
 *    - withTracking: Auto-tracks page views and events
 *    - withErrorBoundary: Catches React errors
 *    - useLoadingWrapper: Manages loading states
 *
 * ✅ Best Practices
 *    - Type safety throughout
 *    - Memoized computed values
 *    - Event tracking for analytics
 *    - Optimistic UI updates
 *    - Error handling
 *    - Loading states
 *    - Clean code structure
 *
 * ============================================================================
 * HOW TO USE THIS PATTERN IN YOUR REFACTORING
 * ============================================================================
 *
 * 1. Setup GraphQL operations (.graphql files)
 * 2. Run codegen: npm run codegen
 * 3. Import generated hooks
 * 4. Add Zustand stores where needed
 * 5. Extract all strings to i18n
 * 6. Wrap component with HOCs
 * 7. Add tracking events
 * 8. Test in dev: npm run dev
 *
 * ============================================================================
 */
