/**
 * 🛠️ Utils Index - ClubManager API
 *
 * Point d'entrée centralisé pour tous les utilitaires
 */

export {
  log,
  error,
  success,
  info,
  warning,
  section,
  subsection,
  step,
  fileCreated,
  fileUpdated,
  fileSkipped,
  dryRun,
  banner,
  summary,
  options,
  examples,
  progress,
  COLORS,
} from './logger.js';

export {
  toPascalCase,
  toCamelCase,
  toKebabCase,
  toSnakeCase,
  toUpperSnakeCase,
  toPlural,
  toSingular,
  capitalize,
  uncapitalize,
  indent,
  toTestFilename,
  toVariableName,
  toClassName,
  cleanDomainName,
  isValidDomainName,
  toDocComment,
} from './string-utils.js';

export {
  fileExists,
  directoryExists,
  createDirectory,
  writeFile,
  readFile,
  copyFile,
  deleteFile,
  listFiles,
  listDirectories,
  resolveProjectPath,
  resolveRoutesPath,
  resolveTestsPath,
  getRelativePath,
  ensureExtension,
  replaceExtension,
  isInDirectory,
  normalizePath,
  readJsonFile,
  writeJsonFile,
} from './file-utils.js';

export default {
  // Logger
  log,
  error,
  success,
  info,
  warning,
  section,
  subsection,
  step,
  fileCreated,
  fileUpdated,
  fileSkipped,
  dryRun,
  banner,
  summary,
  options,
  examples,
  progress,
  COLORS,

  // String Utils
  toPascalCase,
  toCamelCase,
  toKebabCase,
  toSnakeCase,
  toUpperSnakeCase,
  toPlural,
  toSingular,
  capitalize,
  uncapitalize,
  indent,
  toTestFilename,
  toVariableName,
  toClassName,
  cleanDomainName,
  isValidDomainName,
  toDocComment,

  // File Utils
  fileExists,
  directoryExists,
  createDirectory,
  writeFile,
  readFile,
  copyFile,
  deleteFile,
  listFiles,
  listDirectories,
  resolveProjectPath,
  resolveRoutesPath,
  resolveTestsPath,
  getRelativePath,
  ensureExtension,
  replaceExtension,
  isInDirectory,
  normalizePath,
  readJsonFile,
  writeJsonFile,
};
